import os
import sys

from . import scanner
from . import git_utils


def format_context(root, include_git=True, max_files=200, max_lines=200):
    blocks = []

    blocks.append("# Codebase Context\n")
    blocks.append(f"Generated from: `{os.path.abspath(root)}`\n")

    if include_git:
        info = git_utils.get_git_info(root)
        if info.get("remote"):
            blocks.append(f"Remote: `{info['remote']}`")
        if info.get("branch"):
            blocks.append(f"Branch: `{info['branch']}`")
        if info.get("uncommitted"):
            blocks.append(f"\nUncommitted changes:\n```\n{info['uncommitted']}\n```")
        if info.get("recent_commits"):
            blocks.append(f"\nRecent commits:\n```\n{info['recent_commits']}\n```")

    tree = scanner.get_tree(root, max_files=max_files)
    blocks.append(f"\n## Project Structure\n\n```\n{tree}\n```\n")

    key_files = scanner.find_key_files(root)
    blocks.append(f"\n## Key Files\n")

    for rel_path, abs_path in key_files:
        ext = os.path.splitext(rel_path)[1].lower()
        lang_map = {
            ".py": "python", ".js": "javascript", ".ts": "typescript",
            ".tsx": "tsx", ".jsx": "jsx", ".rs": "rust", ".go": "go",
            ".java": "java", ".c": "c", ".cpp": "cpp", ".h": "c",
            ".hpp": "cpp", ".rb": "ruby", ".php": "php", ".swift": "swift",
            ".kt": "kotlin", ".scala": "scala", ".r": "r",
            ".yaml": "yaml", ".yml": "yaml", ".json": "json",
            ".toml": "toml", ".xml": "xml", ".md": "markdown",
            ".html": "html", ".css": "css", ".scss": "scss",
            ".sql": "sql", ".sh": "bash", ".bash": "bash",
            ".zsh": "bash", ".dockerfile": "dockerfile",
            ".txt": "text", ".cfg": "ini", ".ini": "ini",
        }
        lang = lang_map.get(ext, "")
        content = scanner.read_file(abs_path, max_lines=max_lines)
        blocks.append(f"\n### `{rel_path}`\n\n```{lang}\n{content}```")

    blocks.append("\n---\n*Generated by [codecontext](https://github.com/hanu-14/codecontext)*")
    return "\n".join(blocks)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Extract codebase context for AI assistants."
    )
    parser.add_argument(
        "path", nargs="?", default=".",
        help="Project path (default: current directory)"
    )
    parser.add_argument(
        "--no-git", action="store_true",
        help="Skip git information"
    )
    parser.add_argument(
        "--max-files", type=int, default=200,
        help="Maximum files to show in tree (default: 200)"
    )
    parser.add_argument(
        "--max-lines", type=int, default=200,
        help="Maximum lines per file (default: 200)"
    )
    parser.add_argument(
        "--output", "-o",
        help="Write output to file instead of stdout"
    )
    args = parser.parse_args()

    root = os.path.abspath(args.path)
    if not os.path.isdir(root):
        print(f"error: {root} is not a directory", file=sys.stderr)
        sys.exit(1)

    context = format_context(
        root,
        include_git=not args.no_git,
        max_files=args.max_files,
        max_lines=args.max_lines,
    )

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(context)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(context)


if __name__ == "__main__":
    main()
